include /etc/nginx/snippets/ccec-timer/upstreams.conf;

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    server_tokens off;
    client_max_body_size 10m;

    include /etc/nginx/snippets/ccec-timer/security-headers.conf;
    include /etc/nginx/snippets/ccec-timer/app-routes.conf;
}
