CREATE TABLE T_STATION (
  ID NUMBER(18) PRIMARY KEY,
  STATION_CODE VARCHAR2(30) NOT NULL UNIQUE,
  STATION_NAME VARCHAR2(100) NOT NULL,
  LINE_CODE VARCHAR2(30) NOT NULL,
  SCREEN_CODE VARCHAR2(30) UNIQUE,
  SCREEN_IP VARCHAR2(50),
  PLC_CODE VARCHAR2(30) NOT NULL,
  ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE T_CT_CONFIG (
  ID NUMBER(18) PRIMARY KEY,
  CONFIG_VERSION VARCHAR2(50) NOT NULL,
  ENGINE_TYPE VARCHAR2(50),
  STATION_CODE VARCHAR2(30) NOT NULL,
  STANDARD_CT NUMBER(10) NOT NULL,
  WARN_THRESHOLD NUMBER(5,2) DEFAULT 0.70 NOT NULL,
  ALARM_THRESHOLD NUMBER(5,2) DEFAULT 0.90 NOT NULL,
  SOUND_POLICY VARCHAR2(50),
  EFFECTIVE_TIME DATE NOT NULL,
  ENABLED NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE TABLE T_PRODUCTION_RECORD (
  ID NUMBER(18) PRIMARY KEY,
  RECORD_NO VARCHAR2(50) UNIQUE,
  STATION_CODE VARCHAR2(30) NOT NULL,
  SO_NO VARCHAR2(80) NOT NULL,
  ESN_NO VARCHAR2(80) NOT NULL,
  ENGINE_TYPE VARCHAR2(50),
  STANDARD_CT NUMBER(10) NOT NULL,
  ACTUAL_CT NUMBER(10),
  START_TIME DATE NOT NULL,
  END_TIME DATE,
  STATUS VARCHAR2(30)
);

CREATE TABLE T_ALARM_RECORD (
  ID NUMBER(18) PRIMARY KEY,
  ALARM_NO VARCHAR2(50) UNIQUE,
  ALARM_TYPE VARCHAR2(50) NOT NULL,
  ALARM_LEVEL VARCHAR2(20) NOT NULL,
  STATION_CODE VARCHAR2(30),
  ALARM_DESC VARCHAR2(500) NOT NULL,
  START_TIME DATE NOT NULL,
  END_TIME DATE,
  HANDLE_STATUS VARCHAR2(30) DEFAULT 'OPEN'
);

CREATE TABLE T_AUDIT_LOG (
  ID NUMBER(18) PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL,
  USER_NAME VARCHAR2(100),
  OPERATION_TYPE VARCHAR2(50) NOT NULL,
  OBJECT_TYPE VARCHAR2(50),
  OBJECT_ID VARCHAR2(100),
  BEFORE_VALUE CLOB,
  AFTER_VALUE CLOB,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE INDEX IDX_PRD_ST_TIME ON T_PRODUCTION_RECORD(STATION_CODE, START_TIME);
CREATE INDEX IDX_PRD_ESN ON T_PRODUCTION_RECORD(ESN_NO);
CREATE INDEX IDX_ALARM_TIME ON T_ALARM_RECORD(START_TIME, ALARM_TYPE);
CREATE INDEX IDX_AUDIT_TIME ON T_AUDIT_LOG(CREATED_AT, USER_ID);
