CREATE SEQUENCE SEQ_STATION_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CT_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

INSERT INTO T_STATION (ID, STATION_CODE, STATION_NAME, LINE_CODE, SCREEN_CODE, SCREEN_IP, PLC_CODE, ENABLED)
VALUES (SEQ_STATION_ID.NEXTVAL, 'A601', 'Station A601', 'L1', 'SCR-A601', NULL, 'PLC1', 1);

-- 机型+工位（优先）
INSERT INTO T_CT_CONFIG (ID, CONFIG_VERSION, ENGINE_TYPE, STATION_CODE, STANDARD_CT, WARN_THRESHOLD, ALARM_THRESHOLD, SOUND_POLICY, EFFECTIVE_TIME, ENABLED)
VALUES (SEQ_CT_ID.NEXTVAL, 'v1', 'QSK60', 'A601', 180, 0.70, 0.90, NULL, SYSDATE, 1);

-- 工位默认（ENGINE_TYPE 为空时作为次选）
INSERT INTO T_CT_CONFIG (ID, CONFIG_VERSION, ENGINE_TYPE, STATION_CODE, STANDARD_CT, WARN_THRESHOLD, ALARM_THRESHOLD, SOUND_POLICY, EFFECTIVE_TIME, ENABLED)
VALUES (SEQ_CT_ID.NEXTVAL, 'v1', NULL, 'A601', 240, 0.70, 0.90, NULL, SYSDATE, 1);

CREATE SEQUENCE SEQ_PRODUCTION_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALARM_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
