CREATE SEQUENCE SEQ_AUDIT_LOG_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_SECURITY_USER_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE T_SECURITY_USER (
  ID NUMBER(18) PRIMARY KEY,
  USERNAME VARCHAR2(50) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(100) NOT NULL,
  DISPLAY_NAME VARCHAR2(100),
  ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE T_SECURITY_AUTHORITY (
  USERNAME VARCHAR2(50) NOT NULL,
  AUTHORITY VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_SECURITY_AUTH PRIMARY KEY (USERNAME, AUTHORITY),
  CONSTRAINT FK_SECURITY_AUTH_USER FOREIGN KEY (USERNAME) REFERENCES T_SECURITY_USER(USERNAME)
);

CREATE INDEX IDX_SECURITY_AUTHORITY_USER ON T_SECURITY_AUTHORITY(USERNAME);
