-- V8.4.1 / 设计 V1.2 §3.5：黄区=已用时间达标准 CT 的 50%，红区=80%（与 T_CT_CONFIG.WARN_THRESHOLD / ALARM_THRESHOLD 语义一致）
ALTER TABLE T_CT_CONFIG MODIFY WARN_THRESHOLD DEFAULT 0.50;
ALTER TABLE T_CT_CONFIG MODIFY ALARM_THRESHOLD DEFAULT 0.80;

UPDATE T_CT_CONFIG SET WARN_THRESHOLD = 0.50 WHERE WARN_THRESHOLD = 0.70;
UPDATE T_CT_CONFIG SET ALARM_THRESHOLD = 0.80 WHERE ALARM_THRESHOLD = 0.90;
