CREATE TABLE T_WORK_INSTRUCTION (
  ID NUMBER(18) PRIMARY KEY,
  DOC_NO VARCHAR2(50) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  STATION_CODE VARCHAR2(30) NOT NULL,
  ENGINE_TYPE VARCHAR2(50),
  VERSION_NO VARCHAR2(30) NOT NULL,
  CONTENT_TEXT CLOB NOT NULL,
  SAFETY_NOTES CLOB,
  ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
  CREATED_AT DATE DEFAULT SYSDATE NOT NULL,
  UPDATED_AT DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_WORK_INSTRUCTION_ID START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE INDEX IDX_WI_STATION_ENABLED ON T_WORK_INSTRUCTION(STATION_CODE, ENABLED, UPDATED_AT);
CREATE INDEX IDX_WI_DOC_NO ON T_WORK_INSTRUCTION(DOC_NO);
